### PR TITLE
Document team practices

### PR DESCRIPTION
**Pull request by adborden**
Here's an attempt at documenting our team practices. Some of this is borrowed
from [datagov-deploy](https://github.com/GSA/datagov-deploy), but it is largely
documenting what this team is already doing.

I chose to drop the Code Review column. I want to encourage folks to pair and
peer review as part of the work itself (In Progress), this shouldn't be an
after-the-fact step of development. Plus, I have rarely seen any stories in the
Code Review column.

### CODE REVIEW

**Comment by adborden** [comment]
Would love to have something about how user-centered design and research should drive our priorities.

**Comment by adborden** [comment]
Also, we had talked about doing sprint review, but have yet to schedule it. Last sprint we sort of tacked it onto Sprint Planning.

**Comment by adborden** [comment]
Another thing I would like to add is how we handle repos of the various owners. For example, all GSA repos require changes to go through peer review. We can't force that requirement on [CKAN](https://github.com/ckan) or [datopian](https://github.com/datopian) repos. But we should link to _their_ requirements and encourage them to document those practices.

**Comment by avdata99** [comment]
I agree with dropping the _Code Review_ column.
About the Datopian's repos, If we finally decided I can update its setting in order to work as we expect.

**Comment by adborden** [comment]
Thank you for those who had a look. If anyone else has suggestions, please submit a PR.

**Pull request merged**
