### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by adborden**
Add exit criteria that all code should be linted.

### CODE REVIEW

**Comment by adborden** [comment]
Hey team, I kind of overlooked this when creating our new repos. I'd like to enforce code linting on all of our projects. We already do this in datagov-deploy with molecule and ansible-lint. I've added Python linting to a few repos a while back, but haven't added them to all of the Data.gov repos yet.

I was thinking we would only start with new code and add exceptions for existing files. As you touch a repo or a file, you can update it to be included in the linting process.

I'd also like some suggestions on what linters you've used in the past. I'm looking to cover a few bases to be consistent across repos:
- Python
- PHP
- Bash

**Comment by avdata99** [comment]
> what linters you've used in the past. I'm lookin

For the CI of the import harvest sources tool [I used flake8](https://github.com/GSA/catalog.data.gov/blob/master/Makefile#L47). I think it's a good idea for Python.

**Comment by jbrown-xentity** [comment]
Tested flake8, looks good (though there is **a lot** of work to be done in some of those CKAN extension repo's...)

**Comment by FuhuXia** [comment]
We are already using flake8 in molecule/testinfra python code.

**Pull request merged**
